fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Edgar\UserBundle\Entity\User
    registration:
        confirmation:
            enabled: true
    from_email:
        address:        pruebassymfony@gmail.com
        sender_name:    leonohuevon.com