<?php

namespace AppBundle\Repository;


use AppBundle\Entity\Publicacion;
use AppBundle\Entity\Categoria;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

/**
 * CategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function busquedaBuscarTodasLascategorias()
    {
        return $this->createQueryBuilder('categoria')
            ->addOrderBy('categoria.nombre', 'ASC')
            ->leftJoin('categoria.publicaciones', 'publicaciones')
            ->addSelect('publicaciones')
            ->getQuery()
            ;
    }

    public function buscarTodasLasCategorias()
    {
        return $this->busquedaBuscarTodasLascategorias()->execute();
    }

  
    public function todasCategoriasNoUsadas()
    {
        return $this->createQueryBuilder('categoria')
            ->leftJoin('categoria.publicaciones', 'publicaciones')
            ->andWhere('categoria.publicaciones is EMPTY')
            ->getQuery()
            ->execute()
            ;
    }
    

}
