<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ComentarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComentarioRepository extends EntityRepository
{
    public function buscarComentariosPorPublicacion($id)
    {
        return $this->createQueryBuilder('c')
            ->leftJoin('c.publicacion', 'publicacion')
            ->andWhere('publicacion.id = :id')
            ->setParameter('id', $id)
            ->addOrderBy('c.createdAt', 'DESC')
            ->getQuery()
            ;
    }

    public function comentariosPorPublicacion($id)
    {
        return $this->buscarComentariosPorPublicacion($id)->execute();
    }

   

    public function ultimosComentarios()
    {
        return $this->createQueryBuilder('c')
            ->addOrderBy('c.createdAt', 'DESC')
            ->setMaxResults(5)
            ->getQuery()
            ->execute()
            ;
    }
    
    public function todosComentarios(){
        return $this->createQueryBuilder('c')
            ->addOrderBy('c.createdAt', 'DESC')
            ->getQuery()
            ->execute()
            ;
    }
}
