<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * LogroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogroRepository extends \Doctrine\ORM\EntityRepository
{
    public function buscarLogrosDeUnUsuario($id)
    {
        return $this->createQueryBuilder('logro')
            
            ->leftJoin('logro.usuario', 'usuario')
            ->andWhere('usuario.id = :id')
            ->setParameter('id', $id)
            ->addOrderBy('logro.createdAt', 'DESC')
            ->getQuery()
            ->execute()
            ;
    }

    public function LogrosDeUnUsuario($id)
    {
        return $this->buscarLogrosDeUnUsuario($id)->execute();
    }
    
    public function todosLogros()
    {
        return $this->createQueryBuilder('logro')
            ->addOrderBy('logro.id', 'ASC')
            ->leftJoin('logro.usuario', 'usuario')
            ->getQuery()
            ;
    }

    public function logrosTodos()
    {
        return $this->todosLogros()->execute();
    }
}
