<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * LogroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogroRepository extends \Doctrine\ORM\EntityRepository
{
    public function buscarLogrosPorUsuario($id)
    {
        return $this->createQueryBuilder('logro')
            //->select('logro.nombre', 'logro.descripcion', 'logro.createdAt')
            ->leftJoin('logro.usuario', 'usuario')
            ->andWhere('usuario.id = :id')
            ->setParameter('id', $id)
            ->addOrderBy('logro.createdAt', 'DESC')
            ->getQuery()
            ->execute()
            ;
    }

    public function LogrosPorUsuario($id)
    {
        return $this->buscarLogrosPorUsuario($id)->execute();
    }
}
