<?php

namespace AppBundle\Repository;

/**
 * PublicacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicacionRepository extends \Doctrine\ORM\EntityRepository
{
    public function buscarTodasLasPublicaciones()
    {
        return $this->createQueryBuilder('p')
            ->addOrderBy('p.createdAt', 'DESC')
            ->leftJoin('p.categorias', 'categorias')
            ->addSelect('categorias')
            ->leftJoin('p.autor', 'autor')
            ->addSelect('autor')
            ->leftJoin('p.comentarios', 'comentarios')
            ->addSelect('comentarios')
            ->getQuery()
            ;
    }

    public function todaslasPublicaciones()
    {
        return $this->buscarTodasLasPublicaciones()->execute();
    }

    public function buscarPublicacionesQueTieneCategoriaId($nombre)
    {
        $query = $this->createQueryBuilder('p')
            ->leftJoin('p.categorias', 'categorias')
            ->addOrderBy('p.createdAt', 'DESC')
            ->andWhere('categorias.id = :id')
            ->setParameter('id', $nombre)
            ->getQuery()
        ;

        return $query;
    }

    public function PublicacionesQueTieneCategoriaId($nombre)
    {
        return $this->buscarPublicacionesQueTieneCategoriaId($nombre)->execute();
    }
    
    

    public function buscarPublicacionesDeUnUsuarioId($id)
    {
        $qb = $this->createQueryBuilder('p')
            ->leftJoin('p.autor', 'autor')
            ->andWhere('autor.id = :id')
            ->setParameter('id', $id)
            ->addOrderBy('p.createdAt', 'DESC')
            ->addSelect('autor')
            ->getQuery()
            ;
        return $qb;
    }

    public function publicacionesDeUnrUsuarioId($id)
    {
        return $this->buscarPublicacionesDeUnUsuarioId($id)->execute();
    }


    public function topVotosPositivos(){
        return $this->createQueryBuilder('p')

            ->leftJoin('p.categorias', 'categorias')
            ->addSelect('categorias')
            ->leftJoin('p.autor', 'autor')
            ->addSelect('autor')
            ->leftJoin('p.comentarios', 'comentarios')
            ->addSelect('comentarios')
            ->addOrderBy('p.votosPositivos' , 'DESC')

            ->getQuery()
            ->execute()
            ;
    }

    public function votosPositivios()
    {
        return $this->topVotosPositivos()->execute();
    }


    public function topVotosNegativos(){
        return $this->createQueryBuilder('p')

            ->leftJoin('p.categorias', 'categorias')
            ->addSelect('categorias')
            ->leftJoin('p.autor', 'autor')
            ->addSelect('autor')
            ->leftJoin('p.comentarios', 'comentarios')
            ->addSelect('comentarios')
            ->addOrderBy('p.votosNegativos' , 'DESC')

            ->getQuery()
            ->execute()
            ;
    }

    public function votosNegativos()
    {
        return $this->topVotosNegativos()->execute();
    }
    
    
    public function publicacionesSinCategoria(){
        return $this->createQueryBuilder('p')
            ->leftJoin('p.categorias', 'pu')
            ->andWhere('p.categorias is EMPTY' )
            ->getQuery()
            ->execute()
            ;
            
    }
    

}
